// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CacheRepository is an autogenerated mock type for the CacheRepository type
type CacheRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: key
func (_m *CacheRepository) Delete(key string) {
	_m.Called(key)
}

// Has provides a mock function with given fields: key
func (_m *CacheRepository) Has(key string) bool {
	ret := _m.Called(key)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// PrintContent provides a mock function with given fields:
func (_m *CacheRepository) PrintContent() {
	_m.Called()
}

// Set provides a mock function with given fields: key
func (_m *CacheRepository) Set(key string) {
	_m.Called(key)
}
